# Generated by Django 6.0.1 on 2026-02-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
