# Generated by Django 6.0.1 on 2026-02-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='dummy.png', null=True, upload_to='profile_images/'),
        ),
    ]
