# Generated by Django 6.0.1 on 2026-02-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_instagram_url_user_twitter_url_alter_user_id_and_more'),
        ('accounts', '0004_user_last_sleep_time_alter_user_id_and_more'),
    ]

    operations = [
    ]
