# Generated by Django 6.0.1 on 2026-02-01 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 1, 10, 2, 33, 414119, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
