# Generated by Django 6.0.1 on 2026-02-19 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_start_time', models.DateTimeField(verbose_name='就寝時刻')),
                ('sleep_end_time', models.DateTimeField(verbose_name='起床時刻')),
                ('duration_minutes', models.IntegerField(verbose_name='睡眠時間（分）')),
                ('diary', models.TextField(blank=True, verbose_name='日記・メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '睡眠記録',
                'verbose_name_plural': '睡眠記録',
                'ordering': ['-sleep_start_time'],
            },
        ),
    ]
