# Generated by Django 6.0.1 on 2026-02-19 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_start_time', models.DateTimeField()),
                ('exercise_end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('diary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '運動記録',
                'verbose_name_plural': '運動記録',
                'db_table': 'exercise_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseRecordDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(blank=True, choices=[('上腕(二頭・三頭)', [('アームカール', 'アームカール'), ('トライセプスエクステンション', 'トライセプスエクステンション'), ('ディップス', 'ディップス'), ('ケーブルプッシュダウン', 'ケーブルプッシュダウン'), ('ダイヤモンドプッシュアップ', 'ダイヤモンドプッシュアップ')]), ('下半身(脚・臀部)', [('スクワット', 'スクワット'), ('ブルガリアンスクワット', 'ブルガリアンスクワット'), ('ランジ', 'ランジ'), ('レッグプレス', 'レッグプレス'), ('レッグエクステンション', 'レッグエクステンション'), ('レッグカール', 'レッグカール'), ('シシースクワット', 'シシースクワット'), ('ステップアップ', 'ステップアップ'), ('カーフレイズ', 'カーフレイズ'), ('ヒップブリッジ', 'ヒップブリッジ'), ('ヒップスラスト', 'ヒップスラスト'), ('ドンキーキック', 'ドンキーキック'), ('ファイアハイドラント', 'ファイアハイドラント'), ('レッグアダクション', 'レッグアダクション'), ('レッグアブダクション', 'レッグアブダクション'), ('グッドモーニング', 'グッドモーニング')]), ('体幹・腹筋', [('クランチ', 'クランチ'), ('シットアップ', 'シットアップ'), ('レッグレイズ', 'レッグレイズ'), ('ロシアンツイスト', 'ロシアンツイスト'), ('プランク', 'プランク'), ('サイドプランク', 'サイドプランク'), ('フラッターキック', 'フラッターキック'), ('マウンテンクライマー', 'マウンテンクライマー'), ('ドラゴンフラッグ', 'ドラゴンフラッグ'), ('アブローラー', 'アブローラー'), ('デッドバグ', 'デッドバグ')]), ('背中', [('デッドリフト', 'デッドリフト'), ('ラットプルダウン', 'ラットプルダウン'), ('ローイング', 'ローイング'), ('ベントオーバーロウ', 'ベントオーバーロウ'), ('ワンハンドロウ', 'ワンハンドロウ'), ('懸垂', '懸垂'), ('フェイスプル', 'フェイスプル'), ('シュラッグ', 'シュラッグ'), ('バックエクステンション', 'バックエクステンション'), ('スーパーマン', 'スーパーマン')]), ('胸・プッシュ系', [('ベンチプレス', 'ベンチプレス'), ('チェストプレス', 'チェストプレス'), ('ダンベルフライ', 'ダンベルフライ'), ('ペックフライ', 'ペックフライ'), ('インクラインプレス', 'インクラインプレス'), ('プッシュアップ', 'プッシュアップ'), ('ケーブルクロスオーバー', 'ケーブルクロスオーバー')]), ('有酸素・全身', [('ウォーキング', 'ウォーキング'), ('ランニング', 'ランニング'), ('バーピー', 'バーピー'), ('ジャンピングジャック', 'ジャンピングジャック'), ('ハイニー', 'ハイニー'), ('バットキック', 'バットキック'), ('インチワーム', 'インチワーム'), ('ベアクロール', 'ベアクロール'), ('クラブウォーク', 'クラブウォーク'), ('スケーター', 'スケーター')]), ('格闘・コンディショニング', [('シャドーボクシング', 'シャドーボクシング'), ('キックボクシング', 'キックボクシング'), ('サンドバッグ打ち', 'サンドバッグ打ち'), ('エアキック', 'エアキック')]), ('ボディケア・調整', [('ヨガ', 'ヨガ'), ('ピラティス', 'ピラティス'), ('ストレッチ', 'ストレッチ'), ('体操', '体操'), ('太極拳', '太極拳')]), ('水中運動', [('水泳', '水泳'), ('水中ウォーキング', '水中ウォーキング'), ('水中エアロビクス', '水中エアロビクス')]), ('スポーツ', [('テニス', 'テニス'), ('バドミントン', 'バドミントン'), ('卓球', '卓球'), ('バスケットボール', 'バスケットボール'), ('サッカー', 'サッカー'), ('バレーボール', 'バレーボール'), ('野球', '野球'), ('ボウリング', 'ボウリング')]), ('その他', [('その他', 'その他')]), ('eスポーツ', [('League of Legends', 'League of Legends')])], max_length=100, null=True)),
                ('reps', models.PositiveIntegerField(blank=True, null=True, verbose_name='回数')),
                ('exercise_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='exerciseRecord.exerciserecord')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(help_text='運動についての感想')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '感想履歴',
                'verbose_name_plural': '感想履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
