# Generated by Django 4.2.27 on 2026-02-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseRecord', '0003_exerciserecord_reps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exerciserecord',
            options={'ordering': ['-created_at'], 'verbose_name': '運動記録', 'verbose_name_plural': '運動記録'},
        ),
        migrations.RemoveField(
            model_name='exerciserecord',
            name='exercise_type',
        ),
        migrations.AddField(
            model_name='exerciserecord',
            name='exercise_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterModelTable(
            name='exerciserecord',
            table='exercise_records',
        ),
    ]
