# Generated by Django 6.0.1 on 2026-02-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exerciseRecord', '0003_alter_exerciserecord_exercise_type_and_more'),
        ('exerciseRecord', '0004_alter_exerciserecord_options_and_more'),
    ]

    operations = [
    ]
